/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vuepress-plugin-element-ui",
  "description": "vuepress plugin to extend elementui base on markdown-it-container",
  "base": "/vuepress-plugin-element-ui/",
  "pages": [
    {
      "title": "mark",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-24fb49cd",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "mark",
          "slug": "mark"
        },
        {
          "level": 2,
          "title": "标签",
          "slug": "标签"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/lq782655835/vuepress-plugin-element-ui",
    "editLinks": true,
    "docsDir": "docs",
    "editLinkText": "Edit this page on GitHub",
    "lastUpdated": "Last Updated"
  }
}